# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i --production
      # - run: mv .env.prod .env
      - run: pm2 delete flikhs-back 2> /dev/null || true 
      - run: pm2 start 'npm start' --name flikhs-back

